const audios = [
"everything-that's-happening-right-now-is-making-me-stronger",
"i-accomplish-anything-i-focus-on",
"i-am-accept -and-love",
"i-am-blessed-to-have-everything-in-my-life",
"i-am-good-person-who-deserves-success",
"i-am-growing-as-a-person-everyday",
"i-am-happy-with-what-i-have",
"i-am-in-charge-of-my-life",
"i-am-not-afraid-of-failures",
"i-am-not-what-others-think-of-me",
"i-am-proud-of-myself",
"i-am-stronger-than-i-look",
"i-am-sure-i-will-learn-english",
"i-am-taking-action-today",
"i-am-the-architect-of-my-own-life",
"i-am-the-best",
"i-believe-in-myself-and-i-am-motivated",
"i-believe-in-myself-and-the-ability-to-succeed",
"i-can-do-anything-i-focus-on",
"i-forgive-everyone",
"i-forgive-myself-and-others",
"i-have-the-power-to-overcome-obstacles",
"i'm-always-in-the-right-place-at-the-right-time",
"im-constantly-presented-with",
"i-only-focus-on",
"i-see-chanlleges-in-my-life-as-opportunities-for-growth",
"i-will-be-able-to-speak-and-understand-english",
"i-will-live-a-healthy-lifestyle",
"i-will-never-give-up-my-goals-and-dreams",
"i-will-not-settle-for-less-than-i-deserve",
"i-will-stop-thinking",
"i-will-stop-worrying",
"success-is-always-knocking-at-my-door",
"we-are-what-we-think-about",
"what-we-think,we-become"
];


